// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmoka3ebkuSumbelw6YosIaL4CrMqQt18',
    appId: '1:696081762751:web:0e611cb2adbcf5c874390a',
    messagingSenderId: '696081762751',
    projectId: 'fir-database-practice-f45ff',
    authDomain: 'fir-database-practice-f45ff.firebaseapp.com',
    storageBucket: 'fir-database-practice-f45ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXxrQUFrSmNeVyHf3ii8CNGpjmg02eQpU',
    appId: '1:696081762751:android:c37b2b7b0d023f8b74390a',
    messagingSenderId: '696081762751',
    projectId: 'fir-database-practice-f45ff',
    storageBucket: 'fir-database-practice-f45ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHXILWdIdgoACPDS9b48yGAlR98UPrACE',
    appId: '1:696081762751:ios:635293b24ce174cc74390a',
    messagingSenderId: '696081762751',
    projectId: 'fir-database-practice-f45ff',
    storageBucket: 'fir-database-practice-f45ff.appspot.com',
    iosBundleId: 'com.example.fbDbPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHXILWdIdgoACPDS9b48yGAlR98UPrACE',
    appId: '1:696081762751:ios:635293b24ce174cc74390a',
    messagingSenderId: '696081762751',
    projectId: 'fir-database-practice-f45ff',
    storageBucket: 'fir-database-practice-f45ff.appspot.com',
    iosBundleId: 'com.example.fbDbPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmoka3ebkuSumbelw6YosIaL4CrMqQt18',
    appId: '1:696081762751:web:b8fb0eda3aebfa5474390a',
    messagingSenderId: '696081762751',
    projectId: 'fir-database-practice-f45ff',
    authDomain: 'fir-database-practice-f45ff.firebaseapp.com',
    storageBucket: 'fir-database-practice-f45ff.appspot.com',
  );
}
